### PR TITLE
Use FastDDS Sync as default DDS

### PR DESCRIPTION
**Pull request by audrow**
Switching the default DDS to FastDDS Sync after the Technical Steering Committee's recent vote  ([results](https://docs.google.com/presentation/d/19WUgt57s8lBgV_aMFblvo_iwUujLuQVdusC_3DGZwI8/edit#slide=id.gfbb633fe5d_0_19)). You can find the full meeting minutes here: https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2021-11-18/23209.

This PR relies on https://github.com/ros2/rmw_fastrtps/pull/571.

FYI @JaimeMartin and @MiguelCompany.

### CODE REVIEW

**Comment by audrow** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15673/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10351/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/13337/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15902/)

**Comment by emersonknapp** [comment]
Is this change related at all to https://github.com/ros2/ci/issues/601 issue? The Windows CI started failing, and the other activity I see there is related to this. Not sure if that's just a coincidence though

**Comment by emersonknapp** [comment]
@audrow if you're overriding builds when making newer changes, might make sense to cancel the older ones still running in the queue/runners (unless their results are still relevant). There's a pretty big backup right now since a full windows build takes 3+ hrs, it's hard to tell from this context here if all the builds are needed.

**Comment by audrow** [comment]
> @audrow if you're overriding builds when making newer changes, might make sense to cancel the older ones still running in the queue/runners (unless their results are still relevant). There's a pretty big backup right now since a full windows build takes 3+ hrs, it's hard to tell from this context here if all the builds are needed.

@emersonknapp, it's a good suggestion. I don't think I've left any jobs running. I restarted the Windows jobs, since the previous runs already failed and it looks like it was a connectivity issue.

**Comment by emersonknapp** [comment]
Currently still running:
* https://ci.ros2.org/job/ci_windows/15907/
* https://ci.ros2.org/job/ci_windows/15906/
* and currently pending for windows are 3 more builds of the same full-run settings, which will be (if nothing changes) 15910, 15911, 15912

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-12-16-2021/23541/1

**Comment by audrow** [comment]
Here's another run:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15870/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10547/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/13536/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16169/)

**Comment by audrow** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15958/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10631/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16281/)

**Comment by MiguelCompany** [comment]
@audrow I just checked locally that merging eProsima/Fast-DDS#2358 fixes the crash on Windows when the tests of `tf2_ros_py` exit.

**Comment by MiguelCompany** [comment]
@audrow eProsima/Fast-DDS#2358 has just been merged. Please run CI again, thank you

**Comment by clalancette** [comment]
Another try at CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15984/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10654/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16306/)

**Comment by clalancette** [comment]
@MiguelCompany It works!  Thanks for the fix.

Here's a few more jobs now to see where we are at:

* Windows Debug [Build Status](http://ci.ros2.org/job/ci_windows/16320/)
* Linux Clang [Build Status](http://ci.ros2.org/job/ci_linux_clang_libcxx/12/)
* RHEL [Build Status](http://ci.ros2.org/job/ci_linux-rhel/173/)
* Linux packaging [Build Status](http://ci.ros2.org/job/ci_packaging_linux/474/)

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-january-20th-2022/23986/1

**Comment by clalancette** [comment]
All right, with CI mostly green (RHEL is a known problem, and Windows Debug looks a bit flaky), I think we are good to merge this.  I'm going to do that and also merge in https://github.com/ros2/rmw_fastrtps/pull/571 at the same time.

**Review by clalancette — COMMENTED** [review]
Post-hoc approving.

**Pull request merged**
