### PR TITLE
Add allocators for clients and services

### PR DESCRIPTION
**Pull request by esteve**
Add allocators for clients and services

@dirk-thomas @tfoote @wjwwood

### CODE REVIEW

**Comment by wjwwood** [comment]
+1 the changes look ok.

However, this stuff is fairly untested, and some more thought may need to be given to the way I've set these up.

**Comment by tfoote** [comment]
+1

**Comment by dirk-thomas** [comment]
lgtm

**Comment by esteve** [comment]
Thanks.

**Pull request merged**
