### PR TITLE
add RMW_QOS_POLICY_LIVELINESS_UNKNOWN enum

### PR DESCRIPTION
**Pull request by mm318**
This changes adds another `rmw_qos_liveliness_policy_t` enum, one indicating that the liveliness policy is unknown, for use by `get_actual_qos()`.

### CODE REVIEW

**Comment by mm318** [comment]
@thomas-moulard - please run the following CI job:

 * Gist file: *https://gist.githubusercontent.com/mm318/ecabe573be68dc288bdd6ac25b6673f2/raw/d7cf86c904dc16eeb73420a51d59ea5548c4605f/ros2.repos*
 * Additional BUILD flags: --packages-up-to rcl
 * Additional TEST flags: --packages-up-to rcl
 * CI Job: *ci_launcher*

**Comment by thomas-moulard** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/7289/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/3464/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/5964/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/7107/)

**Comment by mm318** [comment]
Hi @thomas-moulard, can you please rerun the CI again? Thanks!

**Comment by thomas-moulard** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/7292/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/3467/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/5967/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/7111/)

**Comment by mm318** [comment]
Hi @thomas-moulard, can you please rerun the CI again with OpenSplice enabled? Thanks!

**Comment by jacobperron** [comment]
I would feel better if we ran CI up to rclcpp too, since it also makes use of the `get_actual_qos` function.

**Comment by mm318** [comment]
@thomas-moulard - please run the following CI job:

 * Gist file: *https://gist.githubusercontent.com/mm318/ecabe573be68dc288bdd6ac25b6673f2/raw/d7cf86c904dc16eeb73420a51d59ea5548c4605f/ros2.repos*
 * Additional BUILD flags: --packages-up-to rclcpp
 * Additional TEST flags: --packages-up-to rclcpp
 * CI Job: *ci_launcher*

Please also enable the use of OpenSplice.

**Comment by thomas-moulard** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/7308/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/3482/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/5982/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/7128/)

**Comment by mm318** [comment]
Hi @jacobperron, can you take a look at the CI results? I think the test failures on Windows are not related to the PRs.

**Comment by jacobperron** [comment]
I haven't seen those failures before, but they do look unrelated. I've triggered a CI job against master with the same configuration to see if it can be reproduced:

[Build Status](https://ci.ros2.org/job/ci_windows/7131/)

**Comment by jacobperron** [comment]
The line that is failing was introduced in https://github.com/ros2/launch/pull/255.

**Pull request merged**
