### PR TITLE
Don't type-erase request header

### PR DESCRIPTION
**Pull request by jacquelinekay**
See discussion in https://github.com/ros2/rcl/pull/30#issuecomment-190446090

### CODE REVIEW

**Comment by esteve** [comment]
+1

**Comment by wjwwood** [comment]
This needs matching changes in all the rmw implementations, but otherwise +1.

**Comment by jacquelinekay** [comment]
other PRs are pending

**Comment by jacquelinekay** [comment]
I think all the necessary PRs are in now.

http://ci.ros2.org/job/ci_linux/1043/
http://ci.ros2.org/job/ci_osx/860/
http://ci.ros2.org/job/ci_windows/1104/

**Pull request merged**
