### PR TITLE
Increase rmw testing coverage above 95%

### PR DESCRIPTION
**Pull request by brawner**
Following up #235, and #236 this PR adds a bit more coverage. With those two and this one, I believe coverage will be boosted above 95%. However, it likely conflicts with #236, and whichever gets approved last will have to be rebased.

Signed-off-by: Stephen Brawner <brawner@gmail.com>

### CODE REVIEW

**Comment by brawner** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/11088/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6396/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9043/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10998/)

**Comment by brawner** [comment]
Moment of truth!

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/11099/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6406/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9056/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11021/)

**Comment by brawner** [comment]
Building again for test_types.cpp
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/11101/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6408/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9058/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11023/)

**Comment by ivanpauno** [comment]
@brawner nit noted when editing changelogs: remember to squash merge instead of using plain merge.

**Comment by brawner** [comment]
@ivanpauno This went in as a regular merge? I'm so sorry. I wish github could just disable that option for me entirely.

**Comment by ivanpauno** [comment]
> @ivanpauno This went in as a regular merge? I'm so sorry. I wish github could just disable that option for me entirely.

Yeah it's a bit annoying, it happens to everybody.
I'm not sure if there is a way to disable merge, that would be pretty interesting.

**Pull request merged**
