### PR TITLE
implement workaround for unresolved symbols problem on Windows

### PR DESCRIPTION
**Pull request by wjwwood**
Connects to ros2/rclcpp#48

Implements a workaround for the fact that the Windows linker cannot handle unresolved symbols when linking a shared library, see: https://github.com/ros2/rclcpp/issues/48#issuecomment-150714947

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Can I assume that the copied CMake code has no changes and therefore doesn't need to be reviewed?

**Comment by wjwwood** [comment]
I didn't change the cmake code in the three cmake files that moved.

**Comment by dirk-thomas** [comment]
lgtm

**Comment by esteve** [comment]
+1

**Pull request merged**
